<?php

/**
 * Created by PhpStorm.
 * User: Rafael
 * Date: 20/3/2017
 * Time: 9:22
 */
class Hilo extends Thread
{
    private $asientos = null;
    private $vector = null;
    private $cont_bola = null;

    public function __construct($parreglo_asientos,$svg,$pcont_bola)
    {
        $this->asientos = $parreglo_asientos;
        $this->vector = $svg;
        $this->cont_bola = $pcont_bola;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if($this->cont_bola < count($this->asientos)){ // si no se han procesado todos los nodos
            echo $this->cont_bola++;

        }else{
            return;
        }
    }



}